// Generated by @wagmi/cli@0.1.11 on 5/15/2023 at 12:02:00 PM

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ILightBulb
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iLightBulbABI = [
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "_msgSender", internalType: "address", type: "address" },
      { name: "lightBulbOwner", internalType: "address", type: "address" },
    ],
    name: "turnOn",
    outputs: [],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IVeaInbox
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iVeaInboxABI = [
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "fnSelection", internalType: "bytes4", type: "bytes4" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "sendMessage",
    outputs: [{ name: "msgId", internalType: "uint64", type: "uint64" }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// LightBulb
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const lightBulbABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "_veaOutbox", internalType: "address", type: "address" },
      { name: "_lightBulbSwitch", internalType: "address", type: "address" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "lightBulbIsOn",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "lightBulbSwitch",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "_msgSender", internalType: "address", type: "address" },
      { name: "lightBulbOwner", internalType: "address", type: "address" },
    ],
    name: "turnOn",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "veaOutbox",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Switch
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const switchABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "_veaInbox", internalType: "address", type: "address" },
      { name: "_lightBulb", internalType: "address", type: "address" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "messageId",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
      {
        name: "lightBulbOwner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "lightBulbToggled",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "lightBulb",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "turnOnLightBulb",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "veaInbox",
    outputs: [
      { name: "", internalType: "contract IVeaInbox", type: "address" },
    ],
  },
] as const
